---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/aywsolutionweli/public_html/appbs.aywsolution.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/aywsolutionweli/web_appbs/
      - /bin/rsync -av ./ $DEPLOYPATH

